app/views/user.py
from os import stat
from os import listdir
from os.path import join
from hashlib import sha512
from logging import getLogger
from datetime import datetime

from flask import Blueprint
from flask import request
from flask import flash
from flask import render_template
from flask import redirect
from flask import url_for

from .. import db
from ..models import User
from ..models import Project
from ..models import Token
from ..models import Deploy
from ..const import PROJECT_MAX
from ..const import DEPLOY_MAX
from ..user import login_required
from ..utils import get_from
from ..utils import logout
from ..utils import delete_user_from_system
from deploy import UPLOAD_DIR
from deploy import create_dir
from deploy.remove import remove_upload_path_with_deploy_id

bp = Blueprint("user", __name__, url_prefix="/user")
logger = getLogger()


@bp.get("/dashboard")
@login_required
def dashboard(user: User):
    p_count = Project.query.filter(
        Project.owner == user.id
    ).count()

    d_count = Deploy.query.filter(
        Deploy.owner == user.id
    ).count()

    PATH: str = join(UPLOAD_DIR, str(user.id))
    create_dir(PATH)

    using_size = 0
    for file in listdir(PATH):
        using_size += stat(join(PATH, file)).st_size

    return render_template(
        "user/dashboard.jinja2",
        user=user,
        using_size=using_size,
        p_count_per=int(p_count / PROJECT_MAX * 100),
        d_count_per=int(d_count / DEPLOY_MAX * 100)
    )


@bp.get("/password-update")
@login_required
def password_update(user: User):
    return render_template(
        "user/password-update.jinja2",
    )


@bp.post("/password-update")
@login_required
def password_update_post(user: User):
    old_password = sha512(request.form.get("old-password", "").encode()).hexdigest()

    if user.password != old_password:
        flash("기존 비밀번호가 일치하지 않습니다.", "user-password-update")
        return redirect(url_for("user.password_update"))

    password = request.form.get("password", "")

    if len(password) < 12:
        flash("12글자 이상으로 긴 비밀번호를 입력해야합니다.", "user-password-update")
        return redirect(url_for("user.password_update"))

    if password != request.form.get("password-check", ""):
        flash("비밀번호가 일치하지 않습니다. 다시 한 번 확인해주세요.", "user-password-update")
        return redirect(url_for("user.password_update"))

    new_password = sha512(password.encode()).hexdigest()

    if new_password == user.password:
        flash("동일한 비밀번호로 변경할 수 없습니다.", "user-password-update")
        return redirect(url_for("user.password_update"))

    user.password = new_password
    user.password_updated_at = datetime.now()
    db.session.commit()

    logger.info(f"User id {user.id} change password from {get_from()}")
    return redirect(url_for("user.dashboard"))


@bp.get("/clean-up")
@login_required
def clean_up(user: User):
    count = 0

    for deploy in Deploy.query.filter(
        Deploy.owner == user.id,
    ).all():
        project = Project.query.with_entities(
            Project.last_deploy,
        ).filter(
            Project.id == deploy.project,
        ).first()

        if project is None:
            raise ValueError("등록된 프로젝트가 아닙니다.")

        if deploy.id != project.last_deploy:
            remove_upload_path_with_deploy_id(user.id, deploy.id)
            logger.info(f"Deploy id {deploy.id} is deleted by {user.id} from {get_from()}")

            db.session.delete(deploy)
            count += 1

    db.session.commit()

    flash(f"<b>{count}개</b>의 미사용 버전이 삭제되었습니다.", "success")
    return redirect(url_for("user.dashboard"))


@bp.get("/delete")
@login_required
def delete(user: User):
    if user.id == 1:
        try:
            user_id = int(request.args.get("user_id", "a"))

            db_user = User.query.filter(
                User.id == user_id
            ).first()

            if db_user is None:
                flash("등록된 계정이 아닙니다.")
                return redirect(url_for("user.dashboard"))
        except ValueError:
            pass

    if user.id == 1:
        flash("관리자 계정은 삭제할 수 없습니다.")
        return redirect(url_for("user.dashboard"))

    delete_list = []
    delete_list.append(f"<b>{user.email}</b> 계정")

    token_c = Token.query.filter(
        Token.owner == user.id
    ).count()

    if token_c != 0:
        delete_list.append(f"<b>{token_c}개+</b>의 배포 토큰")

    deploy_c = Deploy.query.filter(
        Deploy.owner == user.id
    ).count()

    if deploy_c != 0:
        delete_list.append(f"<b>{deploy_c}개+</b>의 배포 버전")

    project_list: list[Project] = Project.query.filter(
        Deploy.owner == user.id
    ).all()

    for project in project_list:
        delete_list.append(f"<b>{project.name}</b> 프로젝트")

    return render_template(
        "user/delete.jinja2",
        delete_list=delete_list
    )


@bp.post("/delete")
@login_required
def delete_post(user: User):
    delete_user_from_system(user)
    logger.info(f"User id {user.id} is deleted from {get_from()}")
    return logout("계정이 삭제되었습니다.", "success")

app/templates/user/dashboard.jinja2
{% extends "layout.jinja2" %}
{% block content %}
<div class="container-fluid px-4 mb-3">
    <h1 class="mt-4">대시보드</h1>
    {% include "lib/flash.jinja2" %}
</div>

<div class="container-fluid px-4">
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">계정 정보</h5>
            <div class="mb-3">
                <label class="form-label"><i class="fas fa-envelope me-1"></i> 이메일</label>
                <input class="form-control" value="{{ user.email|e }}" readonly>
            </div>

            <div class="row row-cols-1 row-cols-md-4">
                <div class="col mb-3">
                    <label class="form-label"><i class="fas fa-calendar me-1"></i> 가입 날짜</label>
                    <input class="form-control" value="{{ user.created_at }}" readonly>
                </div>
                <div class="col mb-3">
                    <label class="form-label"><i class="fas fa-lock-open me-1"></i> 마지막 로그인 날짜</label>
                    <input class="form-control" value="{{ user.last_login_at }}" readonly>
                </div>
                <div class="col">
                    <label class="form-label"><i class="fas fa-lock me-1"></i> 마지막 비밀번호 변경 날짜</label>
                    <input class="form-control" value="{{ user.password_updated_at }}" readonly>
                </div>
            </div>

            <div class="d-flex gap-2">
                <a class="btn btn-primary" href="{{ url_for('user.password_update') }}"><i class="fa-solid fa-key me-1"></i> 비밀번호 변경</a>
                <a class="btn btn-danger" href="{{ url_for('user.delete') }}"><i class="fa-solid fa-trash me-1"></i> 계정 삭제</a>
            </div>
        </div>
    </div>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
        <div class="col">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">사용중인 버전 용량</h5>
                    <p class="lead mb-0">{{ using_size|size2str }}</p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">프로젝트 사용률</h5>
                    <p class="lead">{{ p_count_per }}%</p>

                    {% if p_count_per <= 50 %}
                        {% set color = "bg-success" %}
                    {% elif p_count_per <= 70 %}
                        {% set color = "bg-warning" %}
                    {% else %}
                        {% set color = "bg-danger" %}
                    {% endif %}

                    <div class="progress" role="progressbar">
                        <div class="progress-bar {{ color }}" style="width: {{ p_count_per }}%"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">버전 사용률</h5>
                    <p class="lead">{{ d_count_per }}%</p>

                    {% if d_count_per <= 50 %}
                        {% set color = "bg-success" %}
                    {% elif d_count_per <= 70 %}
                        {% set color = "bg-warning" %}
                    {% else %}
                        {% set color = "bg-danger" %}
                    {% endif %}

                    <div class="progress mb-3" role="progressbar">
                        <div class="progress-bar {{ color }}" style="width: {{ d_count_per }}%"></div>
                    </div>

                    <div class="d-flex gap-2">
                        <a class="btn btn-danger" href="{{ url_for('user.clean_up') }}">미사용 버전 삭제</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/user/delete.jinja2
{% extends "layout.jinja2" %}
{% block content %}
<div class="container-fluid px-4 mb-3">
    <h1 class="mt-4">계정 삭제</h1>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/user/dashboard">대시보드</a></li>
            <li class="breadcrumb-item active">계정 삭제</li>
        </ol>
    </nav>

    <p><b>다음의 요소들이 삭제됩니다.</b></p>

    <div class="card mb-3">
        <div class="card-body">
            <ul class="p-0 m-0 ps-3">
                {% for item in delete_list %}
                    <li>{{ item|safe }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="d-flex gap-2">
        <form method="post">
            <a class="btn btn-primary" href="/user/dashboard"><i class="fa-solid fa-xmark me-1"></i> 취소</a>
            <button class="btn btn-danger"><i class="fa-solid fa-trash me-1"></i> 계정 삭제</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/user/password-update.jinja2
{% extends "layout.jinja2" %}
{% block content %}
<div class="container-fluid px-4 mb-3">
    <h1 class="mt-4">비밀번호 변경</h1>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/user/dashboard">대시보드</a></li>
            <li class="breadcrumb-item active">비밀번호 변경</li>
        </ol>
    </nav>

    {% include "lib/flash.jinja2"%}
</div>

<div class="container-fluid px-4">
    <form method="post">
        <div class="mb-3">
            <label for="old-password" class="form-label"><i class="fa-solid fa-lock-open me-1"></i> 기존 비밀번호</label>
            <input type="password" class="form-control" id="old-password" name="old-password" required>
        </div>

        <div class="mb-3">
            <label for="password" class="form-label"><i class="fa-solid fa-key me-1"></i> 비밀번호</label>
            <input type="password" class="form-control" id="password" name="password" minlength="12" required>
        </div>
        <div class="mb-3">
            <label for="password-check" class="form-label"><i class="fa-solid fa-user-lock me-1"></i> 비밀번호 확인</label>
            <input type="password" class="form-control" id="password-check" name="password-check" minlength="12" required>
        </div>

        <button type="submit" class="btn btn-primary btn-lg"><i class="fa-solid fa-right-to-bracket me-1"></i> 비밀번호 변경</button>
    </form>
</div>
{% endblock %}